### ISSUE TITLE
[FEATURE] Implement a UI Custom Resource Definition

### ISSUE THREAD

**Issue by edenreich** [inference-gateway/operator#10]
## Summary

The Inference Gateway has a UI, it would be cool to also be able to deploy the UI if needed.

The spec could look something like this:

```yaml
apiVersion: core.inference-gateway.com/v1alpha1
kind: UI
metadata:
  name: inference-gateway
  namespace: inference-gateway
spec:
  environment: development
  port: 3000
  gatewayURL:
  storage:
    type: local
  auth:
    enabled: true
    provider: oidc
    oidc:
      issuerURL:
      issuerID:
      issuerSecret
        secretKeyRef:
          name:
          key:
    cookies:
      secure: true
```
