### ISSUE TITLE
[FEATURE] Implement MCP Server Custom Resource Definition

### ISSUE THREAD

**Issue by edenreich** [inference-gateway/operator#11]
### Background

The Inference Gateway supports MCP Servers integration, when enabled the Inference Gateway proxy the request of the user to a dedicated MCP tools via Middleware, aggregate the response and returns it back to the client, this is already implemented on the Inference Gateway.

### Task

In order to make the Operator fully flexible, we should have a Custom Resource Definition for deployment an MCP Server, probably something like this:

```yaml
apiVersion: core.inference-gateway.com/v1alpha1
kind: MCP
metadata:
  name: inference-gateway
  namespace: inference-gateway
  labels:
    core.inference-gateway.com/auto-discovery=true
spec:
  image: mcp/playwright:latest
```

We should think on a label or annotation in a future versions where we can let the operator know that it should automatically discover MCP servers and register them on the gateway by a label or annotations. TBD which other configurations might be needed.
